version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: collabio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  api:
    build: .
    entrypoint: npm run dev
    volumes:
      - ./src:/var/www/app/src
    env_file:
      - .env
    ports:
      - 3333:3000

