version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: collabio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3007:3006"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080


  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    env_file:
      - .env
    ports:
      - 3333:3000
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
